//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cndb.WsApiexamen {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estatus", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Estatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string desc {
            get {
                return this.descField;
            }
            set {
                if ((object.ReferenceEquals(this.descField, value) != true)) {
                    this.descField = value;
                    this.RaisePropertyChanged("desc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblExaman", Namespace="http://schemas.datacontract.org/2004/07/Modelo")]
    [System.SerializableAttribute()]
    public partial class tblExaman : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idExampleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idExample {
            get {
                return this.idExampleField;
            }
            set {
                if ((this.idExampleField.Equals(value) != true)) {
                    this.idExampleField = value;
                    this.RaisePropertyChanged("idExample");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsApiexamen.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AgregarExamen", ReplyAction="http://tempuri.org/IService/AgregarExamenResponse")]
        Cndb.WsApiexamen.Estatus AgregarExamen(int Id, string Nombre, string Descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AgregarExamen", ReplyAction="http://tempuri.org/IService/AgregarExamenResponse")]
        System.Threading.Tasks.Task<Cndb.WsApiexamen.Estatus> AgregarExamenAsync(int Id, string Nombre, string Descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ActualizarExamen", ReplyAction="http://tempuri.org/IService/ActualizarExamenResponse")]
        Cndb.WsApiexamen.Estatus ActualizarExamen(int Id, string Nombre, string Descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ActualizarExamen", ReplyAction="http://tempuri.org/IService/ActualizarExamenResponse")]
        System.Threading.Tasks.Task<Cndb.WsApiexamen.Estatus> ActualizarExamenAsync(int Id, string Nombre, string Descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EliminarExamen", ReplyAction="http://tempuri.org/IService/EliminarExamenResponse")]
        Cndb.WsApiexamen.Estatus EliminarExamen(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EliminarExamen", ReplyAction="http://tempuri.org/IService/EliminarExamenResponse")]
        System.Threading.Tasks.Task<Cndb.WsApiexamen.Estatus> EliminarExamenAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ConsultarExamen", ReplyAction="http://tempuri.org/IService/ConsultarExamenResponse")]
        Cndb.WsApiexamen.tblExaman[] ConsultarExamen(string Nombre, string Descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ConsultarExamen", ReplyAction="http://tempuri.org/IService/ConsultarExamenResponse")]
        System.Threading.Tasks.Task<Cndb.WsApiexamen.tblExaman[]> ConsultarExamenAsync(string Nombre, string Descripcion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Cndb.WsApiexamen.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Cndb.WsApiexamen.IService>, Cndb.WsApiexamen.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Cndb.WsApiexamen.Estatus AgregarExamen(int Id, string Nombre, string Descripcion) {
            return base.Channel.AgregarExamen(Id, Nombre, Descripcion);
        }
        
        public System.Threading.Tasks.Task<Cndb.WsApiexamen.Estatus> AgregarExamenAsync(int Id, string Nombre, string Descripcion) {
            return base.Channel.AgregarExamenAsync(Id, Nombre, Descripcion);
        }
        
        public Cndb.WsApiexamen.Estatus ActualizarExamen(int Id, string Nombre, string Descripcion) {
            return base.Channel.ActualizarExamen(Id, Nombre, Descripcion);
        }
        
        public System.Threading.Tasks.Task<Cndb.WsApiexamen.Estatus> ActualizarExamenAsync(int Id, string Nombre, string Descripcion) {
            return base.Channel.ActualizarExamenAsync(Id, Nombre, Descripcion);
        }
        
        public Cndb.WsApiexamen.Estatus EliminarExamen(int Id) {
            return base.Channel.EliminarExamen(Id);
        }
        
        public System.Threading.Tasks.Task<Cndb.WsApiexamen.Estatus> EliminarExamenAsync(int Id) {
            return base.Channel.EliminarExamenAsync(Id);
        }
        
        public Cndb.WsApiexamen.tblExaman[] ConsultarExamen(string Nombre, string Descripcion) {
            return base.Channel.ConsultarExamen(Nombre, Descripcion);
        }
        
        public System.Threading.Tasks.Task<Cndb.WsApiexamen.tblExaman[]> ConsultarExamenAsync(string Nombre, string Descripcion) {
            return base.Channel.ConsultarExamenAsync(Nombre, Descripcion);
        }
    }
}
